language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --no-default-features --features no_std -v
  - cargo test --no-default-features --features no_std -v
  - cargo doc --no-default-features --features no_std -v
  - cargo build -v
  - cargo test -v
  - cargo doc -v
after_success:
  - curl http://docs.piston.rs/travis-doc-upload.sh | sh
